version: "3.8"
services:
  upload-video:
    container_name: upload-video-service
    build: ./upload-video
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/video?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: farooq
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: farooq
      MYSQL_DATABASE: video
    ports:
      - "3307:3306"
    volumes:
      - mysqldb-data:/var/lib/mysql

  authentication-service:
    build: ./authentication
    container_name: authentication-service


  file-system-service:
    build: ./file-system-service
    container_name: file-system-service
    volumes:
      - video-storage:/app/videos

  video-streaming-service:
    build: ./video-streaming-service
    container_name: video-streaming-service
    restart: on-failure
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/video?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: farooq
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysqldb


volumes:
  mysqldb-data:
  video-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./file-system-service/videos
